# Generated by Django 3.2.12 on 2023-03-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('published_at', models.DateField()),
                ('summary', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.writer')),
            ],
        ),
    ]
